// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-YlxJQA4IJBrJ7lpXkjqQ6PPXAICo1o',
    appId: '1:771636175206:web:7e7e02f886c3e5d148e8a7',
    messagingSenderId: '771636175206',
    projectId: 'ourchat-6189b',
    authDomain: 'ourchat-6189b.firebaseapp.com',
    storageBucket: 'ourchat-6189b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSdwuTJkuskH70sSJn5TuLK6zFqUlu2s',
    appId: '1:771636175206:android:063f01a49b9af54a48e8a7',
    messagingSenderId: '771636175206',
    projectId: 'ourchat-6189b',
    storageBucket: 'ourchat-6189b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_hz7Z5hsJZCn0ntuvYS4zE9mKdHOEf8',
    appId: '1:771636175206:ios:71d5a027ef8f2bd548e8a7',
    messagingSenderId: '771636175206',
    projectId: 'ourchat-6189b',
    storageBucket: 'ourchat-6189b.appspot.com',
    androidClientId: '771636175206-5rbh3v01jtpoav4i0m83e21hof085ejh.apps.googleusercontent.com',
    iosClientId: '771636175206-kbd3u6tbb60imnj24nfm52teq6148aoh.apps.googleusercontent.com',
    iosBundleId: 'com.chat.ourchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT-YlxJQA4IJBrJ7lpXkjqQ6PPXAICo1o',
    appId: '1:771636175206:web:72b304408f8a026148e8a7',
    messagingSenderId: '771636175206',
    projectId: 'ourchat-6189b',
    authDomain: 'ourchat-6189b.firebaseapp.com',
    storageBucket: 'ourchat-6189b.appspot.com',
  );

}